input.onButtonPressed(Button.B, function on_button_pressed_b() {
    
    serial.redirectToUSB()
    serial.writeLine("click b")
    serial.redirect(SerialPin.P0, SerialPin.P1, BaudRate.BaudRate115200)
    serial.writeString("AT" + "\r\n")
    basic.pause(500)
    a = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    b = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    c = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    d = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    serial.redirectToUSB()
    serial.writeLine(a)
    serial.writeLine(b)
    serial.writeLine(c)
    serial.writeLine(d)
    serial.redirect(SerialPin.P0, SerialPin.P1, BaudRate.BaudRate115200)
    serial.writeString("AT+CWMODE=1" + "\r\n")
    basic.pause(500)
    a = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    b = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    c = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    d = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    serial.redirectToUSB()
    serial.writeLine(a)
    serial.writeLine(b)
    serial.writeLine(c)
    serial.writeLine(d)
    serial.redirect(SerialPin.P0, SerialPin.P1, BaudRate.BaudRate115200)
    serial.writeString("AT+RST" + "\r\n")
    basic.pause(5000)
    a = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    b = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    c = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    d = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    serial.redirectToUSB()
    serial.writeLine(a)
    serial.writeLine(b)
    serial.writeLine(c)
    serial.writeLine(d)
    ssid = "WAS"
    pw = "51132079"
    serial.redirect(SerialPin.P0, SerialPin.P1, BaudRate.BaudRate115200)
    serial.writeString("AT+CWJAP=\"WAS\",\"51132079\"" + "\r\n")
    basic.pause(500)
    a = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    b = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    serial.redirectToUSB()
    serial.writeLine(a)
    serial.writeLine(b)
    serial.redirect(SerialPin.P0, SerialPin.P1, BaudRate.BaudRate115200)
    serial.writeString("AT+CIPSTART=\"TCP\",\"52.204.34.129\",80" + "\r\n")
    basic.pause(3000)
    a = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    b = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    serial.redirectToUSB()
    serial.writeLine(a)
    serial.writeLine(b)
    serial.redirect(SerialPin.P0, SerialPin.P1, BaudRate.BaudRate115200)
    let chiamata = "GET /update?api_key=" + "ZMQITLYZ39QKVOM1" + "&field1=22"
    serial.writeString("AT+CIPSEND=" + ("".length + 2) + "\r\n")
    serial.writeString("AT+CIPSTART=\"TCP\",\"52.204.34.129\",80" + "\r\n")
    basic.pause(3000)
    a = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    b = serial.readUntil(serial.delimiters(Delimiters.CarriageReturn))
    serial.redirectToUSB()
    serial.writeLine(a)
    serial.writeLine(b)
    serial.writeLine("fine")
})
let pw = ""
let ssid = ""
let d = ""
let c = ""
let b = ""
let a = ""
serial.writeLine("init")
basic.showIcon(IconNames.Square)
serial.writeLine("provo ad inizializzare ")
